---
- name: Download Logstash Deb Package
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-7.6.2.deb
    dest: /tmp

- name: Install Logstash Deb Package
  become: yes
  apt:
    deb: /tmp/logstash-7.6.2.deb

- name: Create Logstash Pipeline File
  become: yes
  file:
      path: /etc/logstash/conf.d/suricata.conf
      state: touch

- name: Add Logstash Pipeline Configuration
  become: yes
  blockinfile:
      path: /etc/logstash/conf.d/suricata.conf
      marker: ""
      block: |
        input {
          beats {
            port => 5044
            codec => "json_lines"
          }
        }
        filter {
          if [application] == "suricata" {
            date {
              match => [ "timestamp", "ISO8601" ]
            }
            ruby {
              code => "if event['event_type'] == 'fileinfo'; event['fileinfo']['type']=event['fileinfo']['magic'].to_s.split(',')[0]; end;"
            }
          }

          if [src_ip]  {
            geoip {
              source => "src_ip"
              target => "geoip"
              add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
              add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
            }
            mutate {
              convert => [ "[geoip][coordinates]", "float" ]
            }
            if ![geoip.ip] {
              if [dest_ip]  {
                geoip {
                  source => "dest_ip"
                  target => "geoip"
                  add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
                  add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
                }
                mutate {
                  convert => [ "[geoip][coordinates]", "float" ]
                }
              }
            }
          }
        }

        output {
          elasticsearch {
            hosts => ["localhost:9200"]
          }
        }


- name: Start Logstash Service
  become: yes
  service:
    name: logstash
    state: started
